#!/bin/bash

set -eu -o pipefail

IMPL=$(which the-git-annex-remote-ldir)

PY_VER=$(python -c 'import sys; print(sys.version_info.major)')
if [ "$PY_VER" -eq "2" ]
then
    conda-execute -q $IMPL < /dev/null > /dev/null 2> /dev/null
    conda-execute -q $IMPL
else
    $IMPL
fi
